baseURL = 'https://jamessutherland.netlify.app'
languageCode = 'en-uk'
title = 'James Sutherland'
theme = "PaperMod"

[params]
ShowBreadCrumbs = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true


[menu]

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 10
  [[menu.main]]
    identifier = "websitecarbon"
    name = "This Website's Carbon"
    url = "https://www.websitecarbon.com/website/jamessutherland-netlify-app/"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive"
    weight = 10


[params.homeInfoParams]
Title = "Welcome!"
Content = "So glad you're here 🌟"
[[buttons]]
name = "Search"
url = "/search/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/james-sutherland-17879026a/"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/profile.php?id=100005312989146"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/jamessuthers/"


[outputs]
home = [ "HTML", "RSS", "JSON" ]
