baseURL = 'https://jamessutherland.netlify.app'
languageCode = 'en-uk'
title = 'James Sutherland'
theme = "PaperMod"

[params]
ShowBreadCrumbs = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true


[menu]

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 10
  [[menu.main]]
    identifier = "websitecarbon"
    name = "This Website's Carbon"
    url = "https://www.websitecarbon.com"
    weight = 10
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive"
    weight = 10


[params.homeInfoParams]
Title = "Hi there 👋"
Content = "So glad you're here"
[[buttons]]
name = "Search"
url = "/search/"

[[params.socialIcons]]
name = "github"
url = "<link>"

[[params.socialIcons]]
name = "instagram"
url = "https://tesco.com"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
